// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-02-02 17:46:50.428407 +0800 CST m=+0.087414608

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
  "swagger": "2.0",
  "host": "localhost",
  "basePath": "/api/v1",
  "info": {
    "contact": {},
    "description": "An example of gin",
    "license": {
      "name": "MIT",
      "url": "https://github.com/EDDYCJY/go-gin-example/blob/master/LICENSE"
    },
    "termsOfService": "https://github.com/EDDYCJY/go-gin-example",
    "title": "Golang Gin API",
    "version": "1.0"
  },
  "tags": [
    {
      "name": "tag",
      "description": "Everything about your Tags"
    },
    {
      "name": "article",
      "description": "Access to Article"
    }
  ],
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Article parameter",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GetArticle"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Get multiple articles"
      },
      "post": {
        "tags": [
          "article"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Add article"
      }
    },
    "/articles/{id}": {
      "delete": {
        "tags": [
          "article"
        ],
        "parameters": [
          {
            "description": "ID",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Delete article"
      },
      "get": {
        "tags": [
          "article"
        ],
        "parameters": [
          {
            "description": "ID",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Get a single article"
      },
      "put": {
        "tags": [
          "article"
        ],
        "parameters": [
          {
            "description": "ID",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Update article"
      }
    },
    "/tags": {
      "get": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "description": "Name",
            "in": "query",
            "name": "name",
            "type": "string"
          },
          {
            "description": "State",
            "in": "query",
            "name": "state",
            "type": "integer"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Get multiple article tags"
      },
      "post": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/Tag"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Add article tag"
      }
    },
    "/tags/{id}": {
      "delete": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "description": "ID",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Delete article tag"
      },
      "put": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "description": "ID",
            "in": "path",
            "name": "id",
            "required": true,
            "type": "integer"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/Tag"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Update article tag"
      }
    },
    "/tags/export": {
      "post": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/ExportTag"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Export article tag"
      }
    },
    "/tags/import": {
      "post": {
        "tags": [
          "tag"
        ],
        "parameters": [
          {
            "description": "Excel File",
            "in": "body",
            "name": "file",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/app.Response"
            }
          }
        },
        "summary": "Import article tag"
      }
    }
  },
  "securityDefinitions": {
    "token": {
      "type": "apiKey",
      "name": "token",
      "in": "header"
    }
  },
  "definitions": {
    "app.Response": {
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "object"
        },
        "msg": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Tag": {
      "type": "object",
      "required": [
        "name",
        "state"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "created_by": {
          "type": "string"
        }
      }
    },
    "ExportTag": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      }
    },
    "GetArticle": {
      "type": "object",
      "properties": {
        "tag_id": {
          "type": "integer",
          "format": "int64"
        },
        "state": {
          "type": "string"
        },
        "created_by": {
          "type": "string"
        }
      }
    },
    "Article": {
      "type": "object",
      "required": [
        "created_by",
        "state"
      ],
      "properties": {
        "tag_id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "desc": {
          "type": "string",
          "description": "Desc"
        },
        "content": {
          "type": "string",
          "description": "Content"
        },
        "created_by": {
          "type": "string",
          "description": "CreatedBy"
        },
        "state": {
          "type": "string",
          "description": "State"
        }
      }
    }
  }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
